### ISSUE TITLE
swarm/deploy_prometheus.sh improvements

### ISSUE THREAD

**Issue by chrfergen** [clemenko/prometheus#3]
Hi,
let me suggest you 3 improvements for swarm/deploy_prometheus.sh script:

```
#error checking for client bundle
if [ -z $DOCKER_HOST ]; then
  echo "$RED" " Are you using a client bundle? " "$NORMAL"
  exit 1
fi

```

The above check blocks deployment in a SWARM cluster from a SWARM manager node, no DOCKER_HOST and/or client bundle is necessary in that context.

```
echo -n " waiting for grafana to start "
sleep 30

```

"sleep 30" should be replaced with a loop to check if the service is available: in the event of the image must be downloaded from Internet, sometimes 30 seconds are not enough and the following commands will not reach Grafana server

```
echo -n " confgiuring grafana through the api "
curl -skX POST  http://admin:$password@app.dockr.life:3000/api/datasources

```

"app.dockr.life" should be a variable/an argument because it depends from the domain name where swarm cluster is installed.

Regards
Ch.F.

**Comment by clemenko** [comment]
Sorry I missed the issue until now. 
This script is entended to be run from a remote machine with a client bundle. You could simply remove it?

Good point on the `until` statement. 
update coming. 

URL variable added. Update coming.
