### ISSUE TITLE
Grafana json file Dashboards don't work on the newest version of Grafana

### ISSUE THREAD

**Issue by gonzalo-contador** [clemenko/prometheus#6]
Grafana Dashboards cluster json and container.json  dont work on the latest version . Require new json file for swarm. 

thanks

**Comment by clemenko** [comment]
I was able to deploy correctly on a new cluster. How did you deploy prometheus? Did you use the shell script?

**Comment by clemenko** [comment]
![screen shot 2019-03-07 at 9 16 16 am](https://user-images.githubusercontent.com/3177276/53962687-b3bac500-40b9-11e9-8d17-210bb9628158.jpg)

![screen shot 2019-03-07 at 9 16 25 am](https://user-images.githubusercontent.com/3177276/53962689-b4ebf200-40b9-11e9-97d0-42fabb8a9913.jpg)

**Comment by gonzalo-contador** [comment]
fixed the issue. Somehow set -e silenced it and all the other parts of the script the grafana environment worked.
Thanks
